name: StoinkCore
main: com.stoinkcraft.StoinkCore
version: 0.1
api-version: 1.21.8
depend: [Vault]
softdepend: [PlaceholderAPI, Citizens]
commands:
  enterprise:
    description: Enterprise commands
    usage: /enterprise <create/join/info>
    aliases: ['ep','biz','business','corp','llc']
  serverenterprise:
    description: serverenterprise commands
    usage: /serverenterprise
    aliases: [ 'se','serverent','sent' ]
  market:
    description: View item market prices
    usage: /market
    aliases: ['mv','marketvalue','m']
  topceo:
    usage: /topceo spawn <1-3>
    description: Spawn top enterprise CEO NPC
  shares:
    usage: /shares
    description: Opens your share portfolio
    aliases: ['share', 'stonk', 'stonks']
  daily:
    usage: /daily
    description: Opens the daily reward menu

permissions:
  stoinkcore.admin.*:
    description: Allow the use of vein miner for all tool categories
    default: op
    children:
      stoinkcore.admin.reload: true
  stoinkcore.admin.reload:
    description: Allow the use of the reload sub command
    default: op
