name: StoinkCore
main: com.stoinkcraft.StoinkCore
version: 0.1
api-version: 1.21.8
depend: [Vault, PlaceholderAPI, Citizens, FastAsyncWorldEdit, DecentHolograms]
commands:
  enterprise:
    description: Enterprise commands
    usage: /enterprise <create/join/info>
    aliases: ['ep','biz','business','corp','llc']
  serverenterprise:
    description: serverenterprise commands
    usage: /serverenterprise
    aliases: [ 'se','serverent','sent' ]
  market:
    description: View item market prices
    usage: /market
    aliases: ['mv','marketvalue','m']
  topceo:
    usage: /topceo spawn <1-3>
    description: Spawn top enterprise CEO NPC
  shares:
    usage: /shares
    description: Opens your share portfolio
    aliases: ['share', 'stonk', 'stonks']
  daily:
    usage: /daily
    description: Opens the daily reward menu
  pmenu:
    usage: /pmenu
    description: Opens the player upgrade menua
    aliases: ['playermenu', 'playerupgrades', 'upgrades']
  farmland:
    description: Opens the Farmland job site menu
    usage: /farmland
    aliases: ['farm']
    permission: stoinkcore.jobsite.farmland
  quarry:
    description: Opens the Quarry job site menu
    usage: /quarry
    aliases: ['mine']
    permission: stoinkcore.jobsite.quarry
  graveyard:
    description: Opens the Graveyard job site menu
    usage: /graveyard
    aliases: ['grave', 'cemetery']
    permission: stoinkcore.jobsite.graveyard
  stoinkitems:
    description: Admin GUI to spawn custom items
    usage: /stoinkitems
    aliases: ['sitems', 'adminitems']
    permission: stoinkcraft.admin

permissions:
  stoinkcore.protection.bypass:
    description: bypasses jobsite region protections
    default: op
  stoinkcore.admin.*:
    description: Allow the use of vein miner for all tool categories
    default: op
    children:
      stoinkcore.admin.reload: true
  stoinkcore.admin.reload:
    description: Allow the use of the reload sub command
    default: op
  stoinkcraft.admin:
    description: Admin permission for StoinkCraft
    default: op
  stoinkcore.jobsite.*:
    description: Access to all job site commands
    default: true
    children:
      stoinkcore.jobsite.farmland: true
      stoinkcore.jobsite.quarry: true
      stoinkcore.jobsite.graveyard: true
  stoinkcore.jobsite.farmland:
    description: Access to the /farmland command
    default: true
  stoinkcore.jobsite.quarry:
    description: Access to the /quarry command
    default: true
  stoinkcore.jobsite.graveyard:
    description: Access to the /graveyard command
    default: true
